#pragma once

enum {
	COLOR_PAIR_NO_COLOR,
	COLOR_PAIR_CONFIRMATION_DIALOG = 1,
	COLOR_PAIR_INFORMATION_DIALOG,
	COLOR_PAIR_HELP_DIALOG,
	COLOR_PAIR_FORM,
	COLOR_PAIR_FIELD,
	COLOR_PAIR_FIELD_FORE,
	COLOR_PAIR_NOTE_FOCUSED,
	COLOR_PAIR_NOTE_NOT_FOCUSED
};

void init_color_schemes(void);

